### ISSUE TITLE
UML Diagram can overlap menu

### ISSUE THREAD

**Issue by Hyllesen** [Hyllesen/UMLEditor#1]
![capture](https://cloud.githubusercontent.com/assets/9279498/19621703/e1cd70e0-9897-11e6-8002-d7e972152980.PNG)

**Comment by adamsen9** [comment]
Løsning: Lad være med at flytte diagram når mus forlader området?

**Comment by nicklas669** [comment]
Havde du fixet det her @adamsen9 ?

**Comment by adamsen9** [comment]
Jeps, det er fixet!
