### ISSUE TITLE
Application crashes if diagram is loaded by doubleclicking with mouse while over a diagram

### ISSUE THREAD

**Issue by nicklas669** [Hyllesen/UMLEditor#3]
1. Open the "Open" dialog.
2. Position the "Open" dialog so that the file you wish to load is directly on top of a Diagram in the application.
3. Doubleclick the file (so that it loads) - this causes an exception. See image below:

![image](https://cloud.githubusercontent.com/assets/4216390/19742262/7abe1dca-9bc4-11e6-866a-0a6b17331a0c.png)

**Comment by Hyllesen** [comment]
Fixed https://github.com/Hyllesen/UMLEditor/commit/e531fe5f97d2077069ec02e91bc2310f3e44dd33
